#!/bin/sh

# prevent computer from turning off monitor or sleeping
xset -dpms
xset s off

# Add this to your .xinitrc or whatever file starts programs on startup.
# -R restores the last colorscheme that was in use.
wal -R

mpd &			# music player daemon-you might prefer it as a service though
feh --bg-scale ~/.config/wall.png &   # set the background
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
xcompmgr &		# xcompmgr for transparency
#dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
feh --bg-scale ~/.config/wall.png &
exec dwm
